#! /bin/bash

rm ../CSharpHtml/* ../CSharpHtml/*/*
cp -R ../build/html/* ../CSharpHtml/
cp ../build/latex/comp170.pdf ../ProgrammingInCSharp.pdf
#zip rst.zip rst/*.rst rst/conf.py
#mv rst.zip ..
cd ..
rm CSharpHtml.zip
zip -R CSharpHtml.zip CSharpHtml/* CSharpHtml/*/* 
