#! /bin/bash

rm ../CSharpHtml/* ../CSharpHtml/*/*
cp -R rst/_build/html/* ../CSharpHtml/
cp rst/_build/latex/ProgrammingInCSharp.pdf ..
#zip rst.zip rst/*.rst rst/conf.py
#mv rst.zip ..
cd ..
rm CSharpHtml.zip
zip -R CSharpHtml.zip CSharpHtml/* CSharpHtml/*/* 
