name: GitHub Pages and Release PDF

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r ./requirements.txt

      - name: Generate HTML using Sphinx
        run: |
          make html
          echo introcs.cs.luc.edu > build/html/CNAME

      - name: Generate LaTeX using Sphinx
        run: |
          make latex

      - name: make latexpdf via TeXLive
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            make -C build/latex

      - name: Publish HTML to GitHub Pages 
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/html

      - name: Publish PDF to GitHub Releases
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/latex/comp170.pdf
